serenity.project.name=Automatizacion prueba
feature.file.encoding=UTF-8
serenity.report.encoding=UTF-8
coverage.goal=1
coverage.compliance=1
cloud.project=true
serenity.console.headings=ascii
serenity.logging=VERBOSE
serenity.verbose.steps=true
serenity.console.colors=true
serenity.take.screenshots=AFTER_EACH_STEP
serenity.reports.show.step.details=true
serenity.timeout=10000
