#
#Mon Apr 14 00:56:54 COT 2025
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[window-size\=1600,1200, window-size\=1600,1200, remote-allow-origins\=*, --headless\=chrome, --headless], extensions\=[]}
